### ISSUE TITLE
plex_media_quality_total metrics empty 

### ISSUE THREAD

**Issue by rominou99** [ajalewis/plex-media-server-exporter#2]
Hello,
I have deployed the export without any worries, I have all the metrics going up except plex_media_quality_total. Am I missing something or is there a configuration/option on the Plex side?

Below is an extract from the metrics:

```
plex_genres_total{genre="Children",server="PLEX"} 1.0
# HELP plex_sessions_total Total number of current sessions
# TYPE plex_sessions_total gauge
# HELP plex_media_quality_total Total number of media by quality
# TYPE plex_media_quality_total gauge
```

Thanks in any case for your work.

**Comment by ajalewis** [comment]
Hi @rominou99,

Thanks for raising this. Has been fixed in the latest release[ v1.4.0](https://github.com/ajalewis/plex-media-server-exporter/releases/tag/v1.4.0)
