### ISSUE TITLE
Mistmacht ports in Dockerfile and README

### ISSUE THREAD

**Issue by daurpam** [ajalewis/plex-media-server-exporter#5]
Hi, I'm trying to get the best Plex exporter ever and my search got me here 😉 

Testing your code there is a mistmatch with the exposed port in Dockerfile and in the README. 
In the first one you're using **"9299"** to expose, but in examples in README show as **"9922"**.

Hope it can help you!

**Comment by ajalewis** [comment]
Hey @daurpam

Haha thanks for checking it out! I have fixed this mistake in the Dockerfile now.
